"dice.core.builtin.black.ban_rank.banned" = "禁止(-30)"
"dice.core.builtin.black.ban_rank.normal" = "正常(0)"
"dice.core.builtin.black.ban_rank.trusted" = "信任(30)"
"dice.core.builtin.black.ban_rank.warn" = "警告(-10)"
"dice.core.builtin.command.black.add_black_success.info" = "已将用户/群组 %s 加入黑名单，原因: %s"
"dice.core.builtin.command.black.add_reason.default" = "骰主指令"
"dice.core.builtin.command.black.add_trust_success.info" = "已将用户/群组 %s 加入信任列表"
"dice.core.builtin.command.black.help" = "黑名单指令:\n.ban add user <帐号> (<原因>) //添加个人\n.ban add group <群号> (<原因>) //添加群组\n.ban add <统一ID>\n.ban rm user <帐号> //解黑/移出信任\n.ban rm group <群号>\n.ban rm <统一ID> //同上\n.ban list // 展示列表\n.ban list ban/warn/trust //只显示被禁用/被警告/信任用户\n.ban trust <统一ID> //添加信任\n.ban query <统一ID> //查看指定用户拉黑情况\n.ban help //查看帮助\n// 统一ID示例: QQ:12345、QQ-Group:12345"
"dice.core.builtin.command.black.list.info.prefix" = "当前名单:\n"
"dice.core.builtin.command.black.query.found.info.prefix" = "所查询的<%s>情况："
"dice.core.builtin.command.black.query.no_target.info" = "未指定要查询的对象！"
"dice.core.builtin.command.black.query.not_found_normal.info" = "所查询的<%s>情况：正常(0)"
"dice.core.builtin.command.black.query.place_and_reason.postfix" = "\n%s在「%s」，原因：%s"
"dice.core.builtin.command.black.rm_not_found.error" = "找不到用户/群组"
"dice.core.builtin.command.black.rm_success.info" = "已将用户/群组 %s 移出%s列表"
"dice.core.builtin.command.bot.bye.info" = "指令退群: 于群组<%s>(%s)中告别，操作者:<%s>(%s)"
"dice.core.builtin.command.bot.group_work_status.active" = "开启"
"dice.core.builtin.command.bot.group_work_status.inactive" = "关闭"
"dice.core.builtin.command.bot.group_work_status.info" = "\n群内工作状态: "
"dice.core.builtin.command.bot.help" = "骰子管理:\n.bot on/off/about/bye[exit,quit] // 开启、关闭、查看信息、退群"
"dice.core.builtin.command.bot.on.log_on.info.postfix" = "\n请特别注意: 日志记录处于开启状态"
"dice.core.builtin.command.bot.version_latest.info" = "\n最新版本: %s\n"
"dice.core.builtin.command.botlist.add.info" = "新增标记了%d/%d个帐号，这些账号将被视为机器人。\n因此他们被人@，或主动发出指令时，海豹将不会回复。\n另外对于botlist add/rm，如果群里有多个海豹，只有第一个被@的会回复，其余的执行指令但不回应"
"dice.core.builtin.command.botlist.del.info" = "删除标记了%d/%d个帐号，这些账号将不再被视为机器人。\n海豹将继续回应他们的命令"
"dice.core.builtin.command.botlist.help" = ".botlist add @A @B @C // 标记群内其他机器人，以免发生误触和无限对话\n.botlist add @A @B --s  // 同上，不过骰子不会做出回复\n.botlist del @A @B @C // 去除机器人标记\n.botlist list/show // 查看当前列表"
"dice.core.builtin.command.botlist.list.info" = "群内其他机器人列表:\n%s"
"dice.core.builtin.command.dismiss.help" = ".dismiss // 退出当前群，主用于QQ，支持机器人的平台可以直接移出成员"
"dice.core.builtin.command.dismiss.not_mentioned.info" = "[退群指令] 请@我使用这个命令，以进行确认"
"dice.core.builtin.command.find.config.group.info.prefix" = "当前默认搜索分组为"
"dice.core.builtin.command.find.config.group.no_default.info" = "未指定默认搜索分组"
"dice.core.builtin.command.find.config.group.set_default.info.prefix" = "指定默认搜索分组为"
"dice.core.builtin.command.find.config.group.switch.info" = "默认搜索分组由%s切换到%s"
"dice.core.builtin.command.find.config.groupclr.info.prefix" = "已清空默认搜索分组，原分组为"
"dice.core.builtin.command.find.config.groupclr.no_default.info" = "未指定默认搜索分组"
"dice.core.builtin.command.find.config.invalid_option.error" = "设置选项有误"
"dice.core.builtin.command.find.help" = "查询指令，通常使用全文搜索(x86版)或快速查询(arm, 移动版):\n.find/查询 <关键字> // 查找文档。关键字可以多个，用空格分割\n.find #<分组> <关键字> // 查找指定分组下的文档。关键字可以多个，用空格分割\n.find <数字ID> // 显示该ID的词条\n.find --rand // 显示随机词条\n.find <关键字> --num=10 // 需要更多结果\n.find config --group // 查看当前默认搜索分组\n.find config --group=<分组> // 设置当前默认搜索分组\n.find config --groupclr // 清空当前默认搜索分组"
"dice.core.builtin.command.find.reloading.info" = "帮助文档正在重新装载，请稍后..."
"dice.core.builtin.command.find.search.best_result.info" = "最优先结果%s:\n词条: %s:%s\n%s\n\n"
"dice.core.builtin.command.find.search.current_page.info" = "本页结果:\n%s\n"
"dice.core.builtin.command.find.search.detail_hint.info" = "使用\".find <序号>\"可查看明细，如.find 123\n"
"dice.core.builtin.command.find.search.glitch.error" = "%s搜索故障: %s"
"dice.core.builtin.command.find.search.group.info.prefix" = "[搜索分组%s]"
"dice.core.builtin.command.find.search.hint.info" = "[%s]【%s:%s】 匹配度%.2f\n"
"dice.core.builtin.command.find.search.hint_with_group.info" = "[%s][%s]【%s:%s】 匹配度%.2f\n"
"dice.core.builtin.command.find.search.id_format.info" = "词条: %s:%s\n%s"
"dice.core.builtin.command.find.search.id_not_found.error" = "未发现对应ID的词条"
"dice.core.builtin.command.find.search.not_found.error" = "%s未找到搜索结果"
"dice.core.builtin.command.find.search.not_found_on_page.error" = "%s找到%d条结果, 但在当前页码并无结果"
"dice.core.builtin.command.find.search.page_hint.info" = "使用\".find <词条> --page=<页码> 查看更多结果\n"
"dice.core.builtin.command.find.search.page_num.info" = "共%d条结果, 当前显示第%d页(第%d条 到 第%d条)\n"
"dice.core.builtin.command.help.help" = "海豹核心 %s\n官网: sealdice.com\n海豹群: 524364253\n"
"dice.core.builtin.command.help.reload_success.info" = "帮助文档已经重新装载"
"dice.core.builtin.command.help.reloading.info" = "帮助文档正在重新装载，请稍后..."
"dice.core.builtin.command.help.search.glitch.error" = "搜索故障: "
"dice.core.builtin.command.help.search.not_found.error" = "未找到搜索结果"
"dice.core.builtin.command.in_test_mode.error" = "此指令在展示模式下不可用"
"dice.core.builtin.command.permission_required.master.info" = "你不具备Master权限"
"dice.core.main.auto_update.exiting.warn" = "检测到 auto_update.exe，即将自动退出当前程序并进行升级"
"dice.core.main.auto_update.failed.error" = "升级程序检查失败: "
"dice.core.main.auto_update.tips.warn" = "程序目录下会出现“升级日志.log”，这代表升级正在进行中，如果失败了请检查此文件。"
"dice.core.main.cleanup" = "程序即将退出，进行清理……"
"dice.core.main.container_mode.info" = "当前为容器模式，内置适配器与更新功能已被禁用"
"dice.core.main.delete_db_cache_failed.error" = "数据库缓存文件删除失败"
"dice.core.main.delete_db_cache_failed.tooltip.message" = "为避免数据损坏，拒绝继续启动。请检查是否启动多份程序，或有其他程序正在使用数据库文件！"
"dice.core.main.delete_db_cache_failed.tooltip.title" = "数据库缓存文件删除失败"
"dice.core.main.delete_old_helpdoc_failed.error" = "移除旧帮助文档时出错，%v"
"dice.core.main.error.stack" = "异常: %v\n堆栈: %v"
"dice.core.main.fix_log_items_failed.error" = "修正log_items表时出错，%s"
"dice.core.main.logger_start.info" = "核心日志开始记录"
"dice.core.main.migrate_settings_failed.error" = "迁移历史设置项时出错，%s"
"dice.core.main.no_endpoints.info" = "未检测到任何帐号，请先到“帐号设置”进行添加"
"dice.core.main.service_address_setup.info" = "由参数输入了服务地址:"
"dice.core.main.ui.use_external.info" = "检测到外置的UI资源文件，将使用frontend_overwrite文件夹内的资源启动UI"
"dice.core.main.ui.use_internal.info" = "未检测到外置的UI资源文件，将使用内置资源启动UI"
"dice.core.sys_service.install_failed.error" = "安装失败: %s\n"
"dice.core.sys_service.install_success.info" = "安装完成，正在启动……"
"dice.core.sys_service.installing.info" = "正在安装系统服务，安装完成后，SealDice将自动随系统启动"
"dice.core.sys_service.try_access.info" = "正在试图访问系统服务 ..."
"dice.core.sys_service.uninstall_success.info" = "系统服务已删除"
"dice.core.sys_service.uninstalling.info" = "正在卸载系统服务……"
